# Generated by Django 5.0 on 2024-01-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Variant',
            new_name='variant',
        ),
    ]
