# Generated by Django 5.0 on 2024-01-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000022902C74040>', max_length=200),
        ),
    ]
