# Generated by Django 5.0 on 2024-01-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile_otp_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='otp',
            new_name='otp1',
        ),
    ]
