# Generated by Django 5.0 on 2024-01-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile_otp_userprofile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000023F61248040>', max_length=200),
        ),
    ]
