# Generated by Django 5.0 on 2024-01-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000002E363D88040>', max_length=200),
        ),
    ]
