# Generated by Django 5.0 on 2024-01-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_brand_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='battery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='price_modifier',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='variant',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='storage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
