# Generated by Django 5.0 on 2024-01-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_variant_battery_variant_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
