# Generated by Django 5.0 on 2024-01-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_userprofile_age_userprofile_wallet_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='uid',
        ),
    ]
