# Generated by Django 5.0 on 2024-01-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_variant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='image1',
            field=models.ImageField(null=True, upload_to='varient_images'),
        ),
        migrations.AddField(
            model_name='variant',
            name='image2',
            field=models.ImageField(null=True, upload_to='varient_images'),
        ),
        migrations.AddField(
            model_name='variant',
            name='image3',
            field=models.ImageField(null=True, upload_to='varient_images'),
        ),
        migrations.AddField(
            model_name='variant',
            name='image4',
            field=models.ImageField(null=True, upload_to='varient_images'),
        ),
    ]
