# Generated by Django 5.0 on 2024-01-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_variant_image1_variant_image2_variant_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image4',
        ),
    ]
