# Generated by Django 5.0 on 2024-01-05 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_variant_image4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='image1',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(null=True, upload_to='varient_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
