# Generated by Django 5.0 on 2024-01-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_variant_discount_percentage_variant_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
