# Generated by Django 5.0 on 2024-01-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_usercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='description',
            field=models.TextField(default=1),
        ),
    ]
