# Generated by Django 5.0 on 2024-01-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_description_usercart_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='is_checkout_done',
            field=models.BooleanField(default=False),
        ),
    ]
