# Generated by Django 5.0 on 2024-02-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_usercart_is_checkout_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_variant',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
