# Generated by Django 5.0 on 2024-01-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
