# Generated by Django 5.0 on 2024-01-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
